// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS2e05EG_HrNxemG0PBJR7Z6EPAHzP8Ig',
    appId: '1:960605271601:web:495d1ec94bb91066920710',
    messagingSenderId: '960605271601',
    projectId: 'q-cut-f7cb1',
    authDomain: 'q-cut-f7cb1.firebaseapp.com',
    databaseURL: 'https://q-cut-f7cb1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'q-cut-f7cb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_gZV1pn7kQ9rgQL7kNUcKsYJSHXa644c',
    appId: '1:960605271601:android:79832c6f673c230f920710',
    messagingSenderId: '960605271601',
    projectId: 'q-cut-f7cb1',
    databaseURL: 'https://q-cut-f7cb1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'q-cut-f7cb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXVQR78Hg_SFllZi3wOWxk1aGR82wVplM',
    appId: '1:960605271601:ios:af49dea2dec6c8ae920710',
    messagingSenderId: '960605271601',
    projectId: 'q-cut-f7cb1',
    databaseURL: 'https://q-cut-f7cb1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'q-cut-f7cb1.appspot.com',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXVQR78Hg_SFllZi3wOWxk1aGR82wVplM',
    appId: '1:960605271601:ios:af49dea2dec6c8ae920710',
    messagingSenderId: '960605271601',
    projectId: 'q-cut-f7cb1',
    databaseURL: 'https://q-cut-f7cb1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'q-cut-f7cb1.appspot.com',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS2e05EG_HrNxemG0PBJR7Z6EPAHzP8Ig',
    appId: '1:960605271601:web:a9f02263435f4ad9920710',
    messagingSenderId: '960605271601',
    projectId: 'q-cut-f7cb1',
    authDomain: 'q-cut-f7cb1.firebaseapp.com',
    databaseURL: 'https://q-cut-f7cb1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'q-cut-f7cb1.appspot.com',
  );
}
